### ISSUE TITLE
[STYLE] Indent tab size 관련

### ISSUE THREAD

**Issue by yoovin** [UMC-TRIPY/web-front#14]
### 목적

> Indent tab size 통일

### 상세 내용
현재 eslint상 tab size가 2로 적용되어있습니다. 다른분들의 코드를 확인하니 4개로 사용중인데, 이를 몇으로 통일할지 상의해야합니다.

**Comment by rbgksqkr** [comment]
탭 사이즈 4칸을 선호하신다고 하셔서 prettier는 4칸으로 설정해두긴 했는데 2칸으로 되나요??
```js
{
    "semi": true,
    "tabWidth": 4,
    "printWidth": 80,
    "singleQuote": true,
    "trailingComma": "none",
    "jsxSingleQuote": true
}
```

**Comment by yoovin** [comment]
저희 프로젝트 최상단 lint에 외부 설정이 두개가 추가되어있는데 이 확장들 중에 2개로 되어있는 항목이 있는것 같아요.

lint 확장을 바꾸거나 끄고 진행해야 할 것 같습니다.

![image](https://github.com/UMC-TRIPY/web-front/assets/35561369/76989294-56a0-4493-afee-0cb3b48bc887)

**Comment by yoovin** [comment]
일단 저는 끄고 하는거로 진행할게요.
